Changer droit pour la visibilité des entités + vue infos stage etudiant
florentL/toast-next-gen pull request #21
Opened 2017-01-31 16:20 UTC by SandraIsabel

### Trello card

### Preview of the result (if visual changes)

2017-01-31 16:35 UTC, fleboulch requested changes

2017-01-31 16:35 UTC, florentL commented on src/main/webapp/app/entities/convention-stage/convention-stage-detail.html
> +            <span has-authority="ROLE_USER">{{vm.conventionStage.etudiantNom}}</span>
ROLE_USER, !ROLE_ADMIN

2017-02-09 12:46 UTC, SandraIsabel reviewed
La solution pour les droits : vm.account.authorities.indexOf('ROLE_ADMIN') === -1
indexOf retourne "l'index" de l'element qu'on cherche, dans cet cas ROLE_ADMIN, si l'element qu'on cherche n'existe pas dans l'array la fonction indexOf retourn -1

2017-02-10 09:17 UTC, fleboulch approved these changes
Good job :+1:

2017-02-10 09:20 UTC, merged