View old version
florentL/toast-next-gen pull request #38
Opened 2017-02-09 10:43 UTC by quentin29200

### Trello card

### Preview of the result (if visual changes)

2017-02-09 17:47 UTC, SandraIsabel commented on src/main/java/fr/istic/crm/service/dto/EntrepriseDTO.java
> +
je pense que c'est mieux effacer le code qui est en commentaire, sinon pour le reste ça me va

2017-02-09 17:47 UTC, SandraIsabel requested changes

2017-02-09 17:47 UTC, SandraIsabel commented on src/main/java/fr/istic/crm/service/dto/EntrepriseDTO.java
> +
je pense que c'est mieux effacer le code qui est en commentaire, sinon pour le reste ça me va

2017-02-10 10:36 UTC, quentin29200 commented
Done

2017-02-10 12:36 UTC, fleboulch approved these changes
Nice

2017-02-10 12:37 UTC, merged